build:
  box:
    id: "nanshe/nanshe_notebook:latest"
    entrypoint: /opt/conda/bin/tini -- /usr/share/docker/entrypoint.sh

  steps:
    - script:
        name: Ensure clean repo.
        code: |-
          git update-index -q --refresh
    - script:
        name: Python 2 environment version details.
        code: |-
          conda2 list
    - script:
        name: Python 3 environment version details.
        code: |-
          conda3 list
    - script:
        name: Build the Python 2 package and clean up after.
        code: |-
          mv .git/shallow .git/shallow-not || true
          conda2 build nanshe_workflow.recipe
          mv .git/shallow-not .git/shallow || true
          rm -rf /opt/conda2/conda-bld/work/*
    - script:
        name: Build the Python 3 package and clean up after.
        code: |-
          mv .git/shallow .git/shallow-not || true
          conda3 build nanshe_workflow.recipe
          mv .git/shallow-not .git/shallow || true
          rm -rf /opt/conda3/conda-bld/work/*
    - script:
        name: Install for Python 2 and clean up.
        code: |-
          conda2 install -y --use-local nanshe_workflow
          conda2 clean -tipsy
    - script:
        name: Install for Python 3 and clean up.
        code: |-
          conda3 install -y --use-local nanshe_workflow
          conda3 clean -tipsy
    - script:
        name: Restrict OpenBLAS to a single thread.
        code: |-
          export OPENBLAS_NUM_THREADS=1
    - script:
        name: Test notebook(s) on Python 2.
        code: |-
          python2 setup.py test
    - script:
        name: Test notebook(s) on Python 3.
        code: |-
          python3 setup.py test

build_sge:
  box:
    id: "nanshe/nanshe_notebook:sge"
    entrypoint: /opt/conda/bin/tini -- /usr/share/docker/entrypoint.sh /usr/share/docker/entrypoint_2.sh

  steps:
    - script:
        name: Ensure clean repo.
        code: |-
          git update-index -q --refresh
    - script:
        name: Python 2 environment version details.
        code: |-
          conda2 list
    - script:
        name: Python 3 environment version details.
        code: |-
          conda3 list
    - script:
        name: Build the Python 2 package and clean up after.
        code: |-
          mv .git/shallow .git/shallow-not || true
          conda2 build nanshe_workflow.recipe
          mv .git/shallow-not .git/shallow || true
          rm -rf /opt/conda2/conda-bld/work/*
    - script:
        name: Build the Python 3 package and clean up after.
        code: |-
          mv .git/shallow .git/shallow-not || true
          conda3 build nanshe_workflow.recipe
          mv .git/shallow-not .git/shallow || true
          rm -rf /opt/conda3/conda-bld/work/*
    - script:
        name: Install for Python 2 and clean up.
        code: |-
          conda2 install -y --use-local nanshe_workflow
          conda2 clean -tipsy
    - script:
        name: Install for Python 3 and clean up.
        code: |-
          conda3 install -y --use-local nanshe_workflow
          conda3 clean -tipsy
    - script:
        name: Restrict OpenBLAS to a single thread.
        code: |-
          export OPENBLAS_NUM_THREADS=1
    - script:
        name: Test notebook(s) on Python 2.
        code: |-
          python2 setup.py test
    - script:
        name: Test notebook(s) on Python 3.
        code: |-
          python3 setup.py test
