{% set data = load_setup_py_data() %}

package:
  name: nanshe_workflow
  version: {{ data.get("version") }}

source:
  git_url: ..

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - contextlib2
    - scandir
    - numpy
    - psutil
    - nanshe >=0.1.0a54
    - bokeh >=1.0.0
    - future
    - webcolors
    - nbconvert
    - notebook
    - ipyparallel
    - ipywidgets
    - jupyter_contrib_nbextensions
    - nbserverproxy  # [py>=35]
    - dask-core >=0.19.4
    - toolz >=0.7.3
    - python-graphviz
    - pyyaml
    - distributed >=1.22
    - dask-drmaa
    - dask-image
    - dask-ml
    - cloudpickle
    - tifffile
    - imgroi
    - kenjutsu >=0.5.0
    - metawrap
    - mplview
    - xnumpy
    - yail
    - zarr

about:
  home: {{ data.get("url") }}
  license: {{ data.get("license") }}
  license_file: LICENSE.txt
  summary: {{ data.get("summary") }}
